-- Execute the procedures
EXEC XXBCM_DATA_MIGRATION_PKG.XXBCM_ADD_SUPPLIER_ADDRESS;
EXEC XXBCM_DATA_MIGRATION_PKG.XXBCM_ADD_SUPPLIER;
EXEC XXBCM_DATA_MIGRATION_PKG.XXBCM_ADD_SUPPLIER_CONTACT;
EXEC XXBCM_DATA_MIGRATION_PKG.XXBCM_ADD_ORDER_HEADERS;
EXEC XXBCM_DATA_MIGRATION_PKG.XXBCM_ADD_ORDER_LINES;
EXEC XXBCM_DATA_MIGRATION_PKG.XXBCM_ADD_INVOICE_HOLDS;
EXEC XXBCM_DATA_MIGRATION_PKG.XXBCM_ADD_INVOICE_HEADERS;
EXEC XXBCM_DATA_MIGRATION_PKG.XXBCM_ADD_INVOICE_LINES;

-- Select data from the updated tables
SELECT * FROM XXBCM_SUPPLIER_ADDRESS;
SELECT * FROM XXBCM_SUPPLIERS;
SELECT * FROM XXBCM_SUPPLIER_CONTACTS;
SELECT * FROM XXBCM_ORDER_HEADERS;
SELECT * FROM XXBCM_ORDER_LINES;
SELECT * FROM XXBCM_INVOICE_HOLDS;
SELECT * FROM XXBCM_INVOICE_HEADERS;
SELECT * FROM XXBCM_INVOICE_LINES;
